### PR TITLE
Change the fm success rate

### PR DESCRIPTION
**Pull request by rsJuuuuu**

### CODE REVIEW

**Comment by Sundays211** [comment]
Great work, thanks!

**Comment by rsJuuuuu** [comment]
What do you use to edit the javascript files btw?

**Comment by Sundays211** [comment]
Eclipse. Editing Javascript files using Eclipse isn't as nice as for Java files, but Javascript is always going to be more difficult to work with since it's dynamically typed (amongst it's many other quirks).

**Comment by rsJuuuuu** [comment]
Alright thanks

**Pull request merged**
