### PR TITLE
Fix most of pickpocketing

### PR DESCRIPTION
**Pull request by rsJuuuuu**
Make pickpocketing actually work.
Still need to figure out the success rates (normal and multiple loots) and add rest of the npcs configs.
Added api.isFrozen for cancelling thieving action if player is stunned.

### CODE REVIEW

**Comment by Sundays211** [comment]
I wouldn't worry about the checking "isPaused" thing, since clicking on anything should cancel the pause anyway, but nice work otherwise!

**Comment by rsJuuuuu** [comment]
Ok, the isPaused was there already so I didn't remove it as I wasn't sure how it worked. Thanks

**Comment by rsJuuuuu** [comment]
I've finished adding all pickpocketNpcs now, but I'm having trouble figuring out how to make it add the listeners for all npcs. I could get the ids for every single npc but thats quite a few so id rather go by name. So is there a method to get npc by name and if not should I add it or do you have another idea?

How do I apply damage to a player?

**Comment by Sundays211** [comment]
Regarding NPC listeners, there is no method for registering NPC event listeners based off their name. Such method has the potential to cause issues if NPCs have the same name but different functionality. It's ultimately easier just to search for the IDs using the config dumps as a one-off, then you'll never have to worry about them again (in most cases, besides the low-level Man and Woman NPCs, there's only 3 or 4 different NPC types which can be pickpocketted).

Regarding damage, I've added two new API methods: "hitEntity" which applies regular damage and "healEntity" which restores lifepoints.

**Comment by rsJuuuuu** [comment]
Nevermind misread

Thanks

**Pull request merged**
