### PR TITLE
Fix crystal hatchet time and add construction configs. Add runecrafting tiara check

### PR DESCRIPTION
**Pull request by rsJuuuuu**
Fix crystal hatchet time

### CODE REVIEW

**Comment by rsJuuuuu** [comment]
Trying to figure out how to make a pull request from intellij idea, apparently it worked. I'll try to commit something actually useful next :)

**Comment by rsJuuuuu** [comment]
Is api.carriedItemTotal() supposed to count equipment aswell? In other words is the comment on InvRepository.getAmountCarried wrong? As clearly it only returns the number of items in backback.

**Comment by Sundays211** [comment]
Looks like the comment is wrong, and it doesn't actually count equipment. At some stage I want to clean up the inventory-related API methods (as well as separating much of the API into different files, much like the clanAPI and mapAPI), but generally you can use api.itemTotal(player, Inv.EQUIPMENT, itemId) to get the number of items a player has worn (similarly, use Inv.BANK and Inv.BACKPACK for bank and backpack respectively).

**Comment by rsJuuuuu** [comment]
Oh I see. That kinda makes api.wearingItem(player, itemId) (that I added thinking there wasn't anything to achieve that) quite redundant? 

Btw, I think api.pausePlayer(player, duration) is broken as all it seems to do is set the player paused for an infinite amount of time. Is that the method that should be used on things like thieving or firemaking? or is there another method?

**Comment by Sundays211** [comment]
It is, but there's no harm in keeping it in the API. It's less confusing than needing to remember the whole line.

That's actually part of a legacy system which I was in the process of replacing (but must have fallen by the wayside).

"Pause" is supposed to stop the player's current movement until they're unpaused (used generally in modals like input requests & selection dialogs), while "freeze" is supposed to prevent the player from moving for a certain amount of game cycles (using api.freezeEntity).

Additionally, many animations will cause the player to freeze until the animation finishes, and you can use runAnimaton(player, animId, callback) in a script to run a callback function once an animation finishes (NOTE: This isn't an API method, so don't use the "api" prefix).

**Comment by rsJuuuuu** [comment]
How can I unpause the player? And how would you go about making player able to interrupt the firemaking action? As currently when you add logs to bonfire you can't stop it until you run out of logs

Nevermind, didn't see your commit

**Pull request merged**
